include: package:lint/strict.yaml

linter:
  rules:
    sort_pub_dependencies: false
    # Отключено правило сортировки зависимостей pub, так как не требуется в данном проекте.
    directives_ordering: false
    # Отключено правило упорядочения директив, так как не требуется в данном проекте.
    prefer_single_quotes: true
    # Включено предпочтение использования одинарных кавычек для строковых литералов.
    always_use_package_imports: true
    # Включено использование только package: imports, а не относительных импортов.
    empty_statements: true
    # Включено предупреждение об пустых операторах.
    empty_catches: true
    # Включено предупреждение об обработчиках исключений, содержащих пустые блоки.
    empty_constructor_bodies: true
    # Включено предупреждение о пустых конструкторах.
    avoid_empty_else: true
    # Включено предупреждение об else-блоках, содержащих только пустые операторы.
    avoid_classes_with_only_static_members : false
    # Отключено предупреждение о классах, содержащих только статические члены, так как это может быть приемлемо в некоторых случаях.
    curly_braces_in_flow_control_structures: true
    # Включено использование фигурных скобок в структурах управления потоком (if, else, for, while), даже при одном операторе.
    parameter_assignments: false
    # Отключено предупреждение о присвоении параметров, так как это может быть приемлемо в некоторых случаях.

analyzer:
  errors:
    avoid_dynamic_calls: false
    # Отключено предупреждение о динамических вызовах, так как это может быть приемлемо в некоторых случаях.
  exclude:
    - "**/*.g.dart"  # Исключает сгенерированные файлы